# fly.toml app configuration file generated for dev-carbonable-ccrp-app on 2023-06-21T15:59:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dev-carbonable-ccrp-app"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
